### ISSUE TITLE
Get rid of the First Run Wizard

### ISSUE THREAD

**Issue by fmaasde** [Fewiel/EnvironmentServer#70]
All Information should be asked in the CP, when you set up the installation.

A short list what should be asked e.g.:

- Name
- E-Mail
- Shopname
- Install Premium Plugins (all or just some)
- ...

**Comment by pattifix** [comment]
+1

**Comment by Sceebo** [comment]
+1

**Comment by Fewiel** [comment]
Done, but some Versions have trouble with this. 
I add a blacklist with versions that do not work to disable the autoinstaller for these versions.

**Comment by Fewiel** [comment]
Due to a bug in the CLI installation and changes in the commands in older versions, not all versions can be installed automatically. 

Current versions are tested and can be installed automatically. 

For plugin installation, I am waiting for GitLab access. I will do that in Feb/March when I am back at campus.

**Comment by Sceebo** [comment]
The extensions are not required, if you log in with your Shopware account (on the First-Wizard) afterwards, the extensions are loaded directly onto the system and only have to be installed and activated manually.

**Comment by Fewiel** [comment]
Already implemented with the Autoinstaller.

Not possible for all Version. In some Versions, the CLI Installer is not working. 
All newer Versions should work.
